Добавить метод отправки введенного кода подтверждения для восстановления пароля
15web/loymax-php pull request #12
Opened 2024-11-06 13:30 UTC by psprokofiev

2024-11-07 12:32 UTC, pchelk1n requested changes

2024-11-07 12:32 UTC, pchelk1n commented on src/PublicApi/Password.php
> +     * Запускает восстановление пароля
Опять запускает?

2024-11-07 12:32 UTC, pchelk1n commented on src/PublicApi/Password.php
> +     * @see https://docs.loymax.net/xwiki/bin/view/Main/Integration/Ways_to_use_API/API_methods/Methods_of_public_api/Password/#H41743043F44344143A43043544243243E44144144243043D43E43243B43543D4384354
Ссылка на запуск а не подтверждение.

2024-11-07 12:32 UTC, pchelk1n commented on src/PublicApi/Password.php
> +    public function confirmResetPassword(string $notifierIdentity, string $confirmCode, string $newPassword): AccessTokenData
В несколько строк лучше читается, а также будет помещаться в 80 символов.

2024-11-07 20:26 UTC, psprokofiev commented on src/PublicApi/Password.php
> +     * Запускает восстановление пароля
исправил

2024-11-07 20:26 UTC, psprokofiev commented on src/PublicApi/Password.php
> +    public function confirmResetPassword(string $notifierIdentity, string $confirmCode, string $newPassword): AccessTokenData
отрефакторил

2024-11-07 20:26 UTC, psprokofiev commented on src/PublicApi/Password.php
> +     * @see https://docs.loymax.net/xwiki/bin/view/Main/Integration/Ways_to_use_API/API_methods/Methods_of_public_api/Password/#H41743043F44344143A43043544243243E44144144243043D43E43243B43543D4384354
исправил

2024-11-07 20:36 UTC, psprokofiev commented on src/PublicApi/Password.php
> +    public function confirmResetPassword(string $notifierIdentity, string $confirmCode, string $newPassword): AccessTokenData
80 перебор, несмотря на пср  
они тут же пишут про мягкое ограничение, что строка не должна быть больше 80 символов, но можно до 120...

2024-11-08 06:36 UTC, pchelk1n commented on src/PublicApi/Password.php
> +    public function confirmResetPassword(string $notifierIdentity, string $confirmCode, string $newPassword): AccessTokenData
Ну от 3 аргументов точно лучше в несколько строк.

2024-11-08 06:39 UTC, pchelk1n approved these changes

2024-11-08 06:39 UTC, merged