Добавить метод получения купону по номеру
15web/loymax-php pull request #14
Opened 2024-11-08 08:32 UTC by psprokofiev

2024-11-08 11:23 UTC, pchelk1n requested changes

2024-11-08 11:23 UTC, pchelk1n commented on src/PublicApi/Coupons/GetCouponByNumber.php
> +        $apiRequest = (new CreateRequest())(
Assert на $couponNumber забыл?

2024-11-08 14:20 UTC, psprokofiev commented on src/PublicApi/Coupons/GetCouponByNumber.php
> +        $apiRequest = (new CreateRequest())(
ну вообще я проверил, лоймакс принимает пустую строку и просто говорит, что такой купон не найден  
сделаем валидацию за них, добавил ассерт

2024-11-11 08:20 UTC, pchelk1n approved these changes

2024-11-11 08:20 UTC, merged