Добавить сообщение при статусе 401
15web/loymax-php pull request #16
Opened 2024-11-11 07:54 UTC by psprokofiev

2024-11-11 12:48 UTC, pchelk1n requested changes

2024-11-11 12:48 UTC, pchelk1n commented on src/ApiClient/ApiClient.php
> +            HttpStatusCode::HTTP_UNAUTHORIZED => new Unauthorized($response),
Что-то мне это не нравится. Может json_decode лучше делать здесь? К тому же надо бы еще исключение от json_decode обработать.

2024-11-12 09:40 UTC, psprokofiev commented on src/ApiClient/ApiClient.php
> +            HttpStatusCode::HTTP_UNAUTHORIZED => new Unauthorized($response),
json_decode решили оставить внутри исключения  
сериалайзер не нужен, поскольку здесь примитивные декод без дто  
оставили внутри исключения, потому что исключение - эксперт, который решает какое сообщение выводить

2024-11-12 11:59 UTC, pchelk1n approved these changes

2024-11-12 12:00 UTC, merged