docs(exceptions): добавил в аннотации теги @throws
15web/loymax-php pull request #2
Opened 2024-10-01 20:31 UTC by psprokofiev

2024-10-02 10:30 UTC, pchelk1n requested changes

2024-10-02 10:30 UTC, pchelk1n commented on src/PublicApi/Cards.php
> +     * @throws ApiClientException|DenormalizeResponseError|JsonException
Где-то отдельной строкой, где-то через или.

2024-10-02 10:30 UTC, pchelk1n commented on src/ApiClient/ApiClient.php
> +     * @throws JsonException
Тут же вроде нет вообше никакого исключения?

2024-10-02 10:30 UTC, pchelk1n commented on src/Authorization/ConfirmTwoFactorAuthentication.php
> +     * @throws ApiClientException|JsonException
Почему бы вместо JsonException прописать конкретное DeserializeResponseError?

2024-10-02 12:06 UTC, psprokofiev commented on src/ApiClient/ApiClient.php
> +     * @throws JsonException
конструктор BadRequest может выкинуть JsonException

2024-10-02 12:08 UTC, psprokofiev commented on src/Authorization/ConfirmTwoFactorAuthentication.php
> +     * @throws ApiClientException|JsonException
ну вот это JsonException тянется везде от апи клиента, потому что его может выкинуть конструктор BadRequest

2024-10-03 09:04 UTC, pchelk1n approved these changes

2024-10-03 09:04 UTC, merged