Добавить методы прикрепления и выпуска карт
15web/loymax-php pull request #23
Opened 2024-11-14 06:31 UTC by psprokofiev

2024-11-14 14:14 UTC, pchelk1n requested changes

2024-11-14 14:14 UTC, pchelk1n commented on src/PublicApi/Cards/Response/Card.php
> +     * @param non-empty-string $barCode ШК карты
ШК - давай без сокращения напишем

2024-11-14 14:14 UTC, pchelk1n commented on src/PublicApi/Cards/Response/Card.php
> +        #[SerializedName('$type')]
В документации вообще не вижу этого поля. Оно нам нужно?

2024-11-14 17:15 UTC, psprokofiev commented on src/PublicApi/Cards/Response/Card.php
> +        #[SerializedName('$type')]
оно есть, например в [этом методе ](https://docs.loymax.net/xwiki/bin/view/Main/Integration/Ways_to_use_API/API_methods/Methods_of_public_api/Cards/#H41243E43743244043044943043544243843D44443E44043C43044643844E43E43A43044044243543F43E43243D44344244043543D43D43543C44343843443543D44243844443843A43044243E44044343A43044044244B)  
нам оно может пока не нужно  
но мы же сдк пишем без фильтрации что нужно, а что нет  
пусть будет

2024-11-14 17:15 UTC, psprokofiev commented on src/PublicApi/Cards/Response/Card.php
> +     * @param non-empty-string $barCode ШК карты
дописал

2024-11-15 07:25 UTC, pchelk1n commented on src/PublicApi/Cards/Response/Card.php
> +        #[SerializedName('$type')]
Ну раз хочешь оставить, тогда нужен комментарий во всех классах поясняющий что это за поле.

2024-11-15 10:43 UTC, psprokofiev commented on src/PublicApi/Cards/Response/Card.php
> +        #[SerializedName('$type')]
не, тогда уберу лучше

2024-11-15 11:20 UTC, pchelk1n approved these changes

2024-11-15 11:20 UTC, merged