Добавить метод генерации QR-кода для карты по ее внутреннему идентификатору
15web/loymax-php pull request #9
Opened 2024-10-29 12:02 UTC by psprokofiev

2024-10-29 13:24 UTC, pchelk1n requested changes

2024-10-29 13:24 UTC, pchelk1n commented on src/PublicApi/Cards/QrCode.php
> +final readonly class QrCode
Get?

2024-10-29 13:24 UTC, pchelk1n commented on src/PublicApi/Cards/QrCode.php
> +use Studio15\Loymax\PublicApi\Cards\Request\QrCode as QrCodeRequest;
Вроде как запросы имеют постфикс Request, тогда и проблем не будет с алиасами.

2024-10-29 14:39 UTC, psprokofiev commented on src/PublicApi/Cards/QrCode.php
> +final readonly class QrCode
ага

2024-10-29 14:39 UTC, psprokofiev commented on src/PublicApi/Cards/QrCode.php
> +use Studio15\Loymax\PublicApi\Cards\Request\QrCode as QrCodeRequest;
добавил

2024-10-29 14:48 UTC, pchelk1n requested changes

2024-10-29 14:48 UTC, pchelk1n commented on src/PublicApi/Cards.php
> +        $qrCode = new GetQrCode(
$getQrCode

2024-10-29 14:55 UTC, psprokofiev commented on src/PublicApi/Cards.php
> +        $qrCode = new GetQrCode(
исправил

2024-10-30 12:36 UTC, pchelk1n approved these changes

2024-10-30 12:36 UTC, merged